# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cf7fa5a326631ac70b6190889c3921ca9fed648e3d99497519c218d924c5b1b16a1b206304b9d1dfbe6843aae2b08bd609e6e4a58826489da78cdb1d70082b4

test:
  secret_key_base: 2b30b1e472895e2b58385b9f3ed8d082a37f5f2f15e8cec344ec44d0bc4c09a1b0ac575f08bbb24622a744ea121b6ff582d8c14003ebeeeab3c800a0d0016f0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
